### ISSUE TITLE
Feature:  export to MuseScore

### ISSUE THREAD

**Issue by larocquemb** [MatthiasLienhard/flowkey_dl#13]
Would be great if you could support export into MuseScore.  How would you do that?

**Comment by MatthiasLienhard** [comment]
I don't know this program, but from the wikipedia page it looks like it can import midi and similar formats. However, what I am doing here is just grabbing the images and processing them such that they can be printed on a sheet. In order export the notes, you'd need a "optical music recognition" software. However, from my (limited) testing, they do not work very well. Unfortunately, this is not something that can be added easily by me.
