### ISSUE TITLE
Arial font in mac os

### ISSUE THREAD

**Issue by giovixo** [MatthiasLienhard/flowkey_dl#14]
On mac os (12.2.1) the Arial font is not loaded due to a name problem with the font file. To fix it I changed the line 102 in my local file flowkey_dl.py with :

fnt = [ImageFont.truetype("Arial.ttf", sz) for sz in font_size]

**Comment by MatthiasLienhard** [comment]
This font issues with different platforms is really annoying. I hope I found a solution that works cross platforms now, based on matplotlib font_manager. If it does not work, please open new issues.

**Comment by giovixo** [comment]
Thx It works
