### ISSUE TITLE
[Request] Could you provide some documentation?

### ISSUE THREAD

**Issue by fabiorzfreitas** [MatthiasLienhard/flowkey_dl#2]
I can't get this going, not sure if it's because I'm on Windows, or because I'm a bit stupid, haha

Thank you

**Comment by MatthiasLienhard** [comment]
I see what I can do, but can you please describe what you tried and what error messages you got? The app should run on windows, under python3. It depends on some packages, which need to be installed first, so if you see import errors, you should try installing these packages.

**Comment by MatthiasLienhard** [comment]
I added some basic instructions

**Comment by fabiorzfreitas** [comment]
Yeah, I didn't know how to install it and was trying to straight run the script from terminal. Anyway, now I can open a proper issue with the new error, haha
