### ISSUE TITLE
Flowkey Links no longer available

### ISSUE THREAD

**Issue by CLabeck** [MatthiasLienhard/flowkey_dl#21]
Hey,

I have been a casual user of your flowkey downloader - quite a nice idea and very useful as after the initial few rounds of practicing a new song with the video I find it quite annoying to have the screen moving around all the time. All I want is the static notes then... which your program helped solve :)

Only that flowkey seems to have changed the url / way the notes are shown...

Is there a new way you can make your tool work?

Christian

**Comment by MatthiasLienhard** [comment]
Yes, flowkey made it harder to get the url of the underlying images, simply right click does not work anymore. It should still work when looking in the browsers cache. With google-chrome browser, you find it by clicking on the three dots in the top right -> more tools -> developer tools, then on the "sources" tab. Here you should find [flowkeycdn.com](http://flowkeycdn.com/) with a folder /sheets, with all the songs from the last session. Click right on the first image (0.png) and  then 'copy link location'.
There is probably similar ways in other browsers.

**Comment by CLabeck** [comment]
Brilliant - worked like a charm and I learned something on top. Your tool is great, a real help! Thanks!

Von meinem iPad gesendet

**Comment by MatthiasLienhard** [comment]
Added this to the readme.
