### ISSUE TITLE
Links to the sheets no longer available

### ISSUE THREAD

**Issue by lmiroslaw** [MatthiasLienhard/flowkey_dl#23]
Has anyone noticed that the sheets are now cut into random pieces, one-two tacts each?
At least this is what I see in my "Developer Tools"-> Page Source section:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/431978/236770137-8bb1aac0-0ed9-42d4-bafe-5da6a0e31d1d.png">

**Comment by MatthiasLienhard** [comment]
I am not sure what you are saying.  Sheets where always cut in patches by flowkey, they get put together again in flowkey-dl. Or are you suggesting the patches are not in the right order, e.g. 0.png is not the first patch?
This I have not observed yet.

**Comment by MatthiasLienhard** [comment]
Please reopen if this issue persists, and provide additional information.
