### ISSUE TITLE
Hallo Matthias

### ISSUE THREAD

**Issue by TheBigGreekLover** [MatthiasLienhard/flowkey_dl#28]
Ich habe versucht das Programm nach deiner Anleitung mit Windows ans Laufen zu bringen. Wenn ich die Python-Datei flowkey_dl anklicke, öfnet sich die Datei für einen Bruchteil einer Sekunde und schließt sich sofort wieder. Zum Öffnen der Datei habe ich bisher Python3.1 sowie die Windows cmd-Umgebung ausprobiert. Beides ohne Erfolg. Weißt du was ich sonst noch ausprobieren kann?

**Comment by MatthiasLienhard** [comment]
Hi, ich kenne mich mit Windows nicht aus, aber entweder 
``` bash
flowkey-dl
```
 in der cmd Umgebung eingeben (mit - und ohne erweiterung, oder flowkey_dl_gui.py anklicken (eventuell wird die Erweiterung '.py' von windows versteckt) sollte funktionieren. Gegebenenfalls ist Rechtsklick: oeffnen mit -> python.exe notwendig. Oder in der cmd Umgebung 
``` bash
python3 flowkey_dl_gui.py
```
