### ISSUE TITLE
error with the cli when i try to load images

### ISSUE THREAD

**Issue by axel584** [MatthiasLienhard/flowkey_dl#31]
![image](https://github.com/MatthiasLienhard/flowkey_dl/assets/1334088/cdc51ef6-3e43-42a3-98cc-9847ab7c0fc6)

**Comment by MatthiasLienhard** [comment]
This seems to be the same issue as in #30, right?

**Comment by axel584** [comment]
I clone the project and when I run it, it's work...
So, it's an old bug...
Sorry.
