### ISSUE TITLE
/sheets/... no longer available?

### ISSUE THREAD

**Issue by Kaipert7** [MatthiasLienhard/flowkey_dl#34]
![grafik](https://github.com/MatthiasLienhard/flowkey_dl/assets/149567504/c8ddb1fa-ac3b-4825-8ae3-f5e35c54f677)

I no longer see the entry where I could load the link for the app. I tried different browsers and also older versions. The /sheets/ ... directory cannot be found. Has Flowkey adjusted something so that the download is no longer possible?

**Comment by hannah-jj** [comment]
This is true for all news songs recently posted.  You can get the image url programmatically too. Try these commands in the console of the web browser:
```
var img = document.querySelector("div.sheet-image");
var imgUrl = img.style.backgroundImage.slice(4, -1).replace(/"/g, "");
console.log(imgUrl);
```
![Screenshot 2023-12-10 at 10 24 46 AM](https://github.com/MatthiasLienhard/flowkey_dl/assets/24800441/2866cb56-47dd-407e-a371-d727e03f710c)

Same issue as reported here - https://github.com/MatthiasLienhard/flowkey_dl/issues/33

**Comment by Kaipert7** [comment]
Hi Hannah, thanks for the Information.
Frank

**Comment by MatthiasLienhard** [comment]
Thats cool! I updated the readme file.
