### ISSUE TITLE
I get this error RuntimeError: tk.h version (8.5) doesn't match libtk.a version (8.6)

### ISSUE THREAD

**Issue by axel-sirota** [MatthiasLienhard/flowkey_dl#38]
I get this error when trying to turn up the UI

**Comment by MatthiasLienhard** [comment]
I think this is unrelated to this package, but to tkinter and python setup. Did you try the suggested procedures on stackoverflow etc.? E.g. https://stackoverflow.com/questions/60469202/unable-to-install-tkinter-with-pyenv-pythons-on-macos
