### ISSUE TITLE
Cannot save the sheet

### ISSUE THREAD

**Issue by krambono** [MatthiasLienhard/flowkey_dl#6]
Hello,

I tried to save the sheet but it didn't work. I saw that the "raw" directory was missing causing the "No such file or directory" error. After I created it, I had no more problems.

**Comment by MatthiasLienhard** [comment]
How did you install the package? Did you use pip? Where did you create it?

**Comment by krambono** [comment]
I used pip. I got this error :
https://github.com/MatthiasLienhard/flowkey_dl/issues/5#issuecomment-752677830

**Comment by MatthiasLienhard** [comment]
The intention is that the raw directory is created during installation using pip - for me it works, no idea why it does not on other systems. If you find a hint whats missing please let me know and I'll add it.

**Comment by MatthiasLienhard** [comment]
Should be fixed in v0.0.3
